### ISSUE TITLE
NullPointerException in TableViewSpanSelectionModel.select

### ISSUE THREAD

**Issue by xylo** [controlsfx/controlsfx#1355] opened 2021-03-23 09:56 UTC
controlsfx: 8.40.18

When a span column is placed at the end of a row the right navigation throws a NullPointerException when span column is selected and the right arrow key is pressed.

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at impl.org.controlsfx.spreadsheet.TableViewSpanSelectionModel.select(TableViewSpanSelectionModel.java:330)
	at impl.org.controlsfx.spreadsheet.TableViewSpanSelectionModel.clearAndSelect(TableViewSpanSelectionModel.java:757)
	at javafx.scene.control.TableView$TableViewSelectionModel.clearAndSelect(TableView.java:1914)
	at impl.org.controlsfx.spreadsheet.GridViewBehavior.selectCell(GridViewBehavior.java:325)
	at com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.selectRightCell(TableViewBehaviorBase.java:888)
	at com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.callAction(TableViewBehaviorBase.java:160)
	at com.sun.javafx.scene.control.behavior.BehaviorBase.callActionForEvent(BehaviorBase.java:218)
	at com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.callActionForEvent(TableViewBehaviorBase.java:208)
	at com.sun.javafx.scene.control.behavior.BehaviorBase.lambda$new$118(BehaviorBase.java:135)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$344(GlassViewEventHandler.java:248)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
```

== How to reproduce ==
1. Create a spreadsheet with a span column at the end of a row:
```
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.controlsfx.control.spreadsheet.*;

import java.util.ArrayList;

public class SpreadsheetViewBug extends Application {

	@Override
	public void start(Stage stage) throws Exception {
		final ArrayList<ObservableList<SpreadsheetCell>> rows = new ArrayList<>();
		final SpreadsheetCell spanCell = SpreadsheetCellType.STRING.createCell(0, 0, 1, 2, "1");
		final SpreadsheetCell fillCell = SpreadsheetCellType.STRING.createCell(0, 1, 1, 1, "2");

		rows.add(FXCollections.observableArrayList(spanCell, fillCell));

		final Grid grid = new GridBase(1, 2);
		grid.setRows(rows);
		grid.spanColumn(2, 0, 0);

		final SpreadsheetView spreadsheetView = new SpreadsheetView(grid);;

		stage.setScene(new Scene(spreadsheetView));
		stage.show();
	}

}
```
2. Start the app and select the the cell that spans multiple columns.
3. Press the right arrow button

**Comment by abhinayagarwal** [comment] 2021-03-26 06:49
This issue is present in ControlsFX 8.40.18 and not present in 11.1.0.

Since all our development efforts are towards 11, bugs for 8 won't be fixed.

**Comment by xylo** [comment] 2021-03-26 16:26
I just updated my project to controlsfx 11.1.0 and I experienced the same bug.  Only the line numbers in the stack trace changed:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at impl.org.controlsfx.spreadsheet.TableViewSpanSelectionModel.select(TableViewSpanSelectionModel.java:331)
	at impl.org.controlsfx.spreadsheet.TableViewSpanSelectionModel.clearAndSelect(TableViewSpanSelectionModel.java:758)
	at javafx.controls/javafx.scene.control.TableView$TableViewSelectionModel.clearAndSelect(TableView.java:1969)
	at impl.org.controlsfx.spreadsheet.GridViewBehavior.selectCell(GridViewBehavior.java:325)
	at javafx.controls/com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.selectRightCell(TableViewBehaviorBase.java:848)
	at javafx.controls/com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.lambda$new$8(TableViewBehaviorBase.java:151)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
	at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2121)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:547)
	at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:971)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by abhinayagarwal** [comment] 2021-03-29 06:09
Alright, I can reproduce this. This can be prevented by a `null` check. Would you be willing to create a PR for this?

**Comment by xylo** [comment] 2021-03-29 08:33
> Alright, I can reproduce this. This can be prevented by a `null` check. Would you be willing to create a PR for this?

OK.

**Closed** 2021-05-20 04:02 UTC
