### ISSUE TITLE
AutoComplete popup does not support RTL layout

### ISSUE THREAD

**Issue by stirante** [controlsfx/controlsfx#1247] opened 2020-04-07 22:08 UTC
I'm trying to implement a language with right to left layout in my app. I set NodeOrientation of the entire scene to RIGHT_TO_LEFT as proposed in #464, but it did not work as it should.

Left to right layout:
![image](https://user-images.githubusercontent.com/2420740/78723906-998e8e80-792c-11ea-9577-2d6188b3ffb8.png)

Right to left layout:
![image](https://user-images.githubusercontent.com/2420740/78723987-c3e04c00-792c-11ea-9237-b06dda15ab12.png)

Popup is in incorrect location. I'm using 11.0.0 controlsfx version, AdoptOpenJDK 12 and JavaFX 12.0.1

**Comment by stirante** [comment] 2020-04-08 21:20
I tried fixing it locally, and this patch works:
`Index: controlsfx/src/main/java/impl/org/controlsfx/skin/AutoCompletePopup.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- controlsfx/src/main/java/impl/org/controlsfx/skin/AutoCompletePopup.java	(revision d72684ba83d8c76f78320b0cc2cff5318f02a79c)
+++ controlsfx/src/main/java/impl/org/controlsfx/skin/AutoCompletePopup.java	(date 1586380423261)
@@ -36,6 +36,7 @@
 import javafx.event.Event;
 import javafx.event.EventHandler;
 import javafx.event.EventType;
+import javafx.geometry.NodeOrientation;
 import javafx.scene.Node;
 import javafx.scene.control.PopupControl;
 import javafx.scene.control.Skin;
@@ -147,7 +148,7 @@
         this.show(
                 parent,
                 parent.getX() + node.localToScene(0, 0).getX() +
-                node.getScene().getX(),
+                node.getScene().getX() - (node.getScene().getNodeOrientation() == NodeOrientation.RIGHT_TO_LEFT ? node.getLayoutBounds().getWidth() : 0),
                 parent.getY() + node.localToScene(0, 0).getY() +
                 node.getScene().getY() + node.getBoundsInParent().getHeight());
 
`

But I don't think it's the cleanest solution possible.

**Comment by Maxoudela** [comment] 2020-04-10 09:18
Thanks for the bug report.
It would be interesting to see how internal javaFX component are dealing with right to left when showing a popup. I wonder if they are native javaFX components doign something similar so that we could look in the code?

Anyway, can you open a PR linking to this issue ? That's always a good start to have a PR and discuss on it directly

**Comment by abhinayagarwal** [comment] 2020-04-13 05:46
This has been fixed in 9.0.0 but still needs to be fixed in master branch.

**Comment by stirante** [comment] 2020-04-18 14:27
I managed to make a fix, that works for both branches:
https://github.com/stirante/controlsfx/commit/d343c2aaa3beb0d760d1f8848effdf722f58567c
https://github.com/stirante/controlsfx/commit/15121e3f07a3db9d1a311eec0dcf02d24f59dd75

Couldn't really find any better looking one, since `getWidth()` returns 0 before `show()`

**Comment by Maxoudela** [comment] 2020-04-20 09:50
In your fix, you are changing the x anchor everytime the width is changing. Wouldn't be sufficient to only set it once?

The issue is that width is equal to 0 at first. Can't you wait till it's not 0, then set the anchor X properly and remove the listener?

Maybe set the listener only when RTF is set because the listener is here for that specific case also no?

**Comment by stirante** [comment] 2020-04-20 10:47
I tried setting it once, when it wasn't 0 and removing listener, but weirdly enough, it didn't work. While tinkering with it a bit, I found that I can just change AnchorLocation of the window and it does the job perfectly.

https://github.com/stirante/controlsfx/commit/bac8ee3157ab8c141f857f1b03d1c056349b20e2
https://github.com/stirante/controlsfx/commit/99e9eb8973553d7bb67a799f0797e9e9188fe63f

**Comment by Maxoudela** [comment] 2020-04-20 11:24
This solution seems better indeed

**Closed** 2020-04-21 14:04 UTC
Labels: bug
