### ISSUE TITLE
Dynamic addition of rows and columns in SpreadsheetView

### ISSUE THREAD

**Issue by gchariharan** [controlsfx/controlsfx#1264] opened 2020-05-01 06:26 UTC
I wonder why SpreadsheetView is not supporting dynamic addition of rows and columns. This is the basic functionality of excel and if you are calling this Spreadsheet, then it should be supported.

**Comment by Maxoudela** [comment] 2020-05-01 10:34
Duplicate of #781

**Closed** 2020-05-01 10:34 UTC
