### ISSUE TITLE
Java 11, JavaFX 11 and ControlsFX

### ISSUE THREAD

**Issue by jschlade** [controlsfx/controlsfx#1100] opened 2019-01-18 17:35 UTC
Hi All,

First of all I wanted to thank everyone who works on these controls. These are some of the best controls out there and I appreciate everything you all do!

So I'm working on a Java 11, JavaFX 11 project and I want to use these controls but I'm dying here. I've had to download the ControlsFX 9 branch and merge in changes to get fixes, etc. This is not something I'm an expert at and I can't upload these changes in anyway... (and I don't know if I should be doing that anyway).

But regardless. My question is when will there be a Java 11, JavaFX 11 branch that has everything? I know it's coming but when? :-)

Thank you all

**Comment by klausenbusk** [comment] 2019-01-20 20:30
I think JavaFX 11 is already supported (https://bitbucket.org/controlsfx/controlsfx/pull-requests/720), we just need a new release with the updated code.

**Comment by jschlade** [comment] 2019-01-20 22:06
Yes, JavaFX 11 does work (with the 9.0.0 branch) but we need a branch on GitHub (Bitbucket is no longer used) that has this PLUS ALL THE FIXES like list-selection-view-actions (https://github.com/controlsfx/controlsfx/compare/9.0.0...list-selection-view-actions), etc. that have been merge into the main branch.

**Comment by pidzama** [comment] 2019-02-05 12:51
When such a release could be expected?

**Comment by initialflame** [comment] 2019-02-07 07:40
We are waiting also for Java 11 Support... So when it comes ?

**Comment by JonathanGiles** [comment] 2019-02-07 07:41
It's coming really soon folks... Hang in there! :-)

**Comment by zcaudate** [comment] 2019-02-15 03:54
ahhh.... we need it now!

**Comment by abhinayagarwal** [comment] 2019-02-15 05:03
Please test ControlsFX for 11 using the snapshot version - https://oss.sonatype.org/content/repositories/snapshots/org/controlsfx/controlsfx/9.0.1-SNAPSHOT/

We are trying to release the same in some time.

**Comment by zcaudate** [comment] 2019-02-15 05:07
ah awesome - will do. It'd also be great if the javadocs were bundled with the jar (or at least downloadable as well as online viewable)

dash is a big part of my workflow and currently controlsfx is not supported as it cannot find the javadoc:

<img width="739" alt="screen shot 2019-02-15 at 1 05 17 pm" src="https://user-images.githubusercontent.com/1455572/52835704-8ade8a00-3122-11e9-8b79-29f9e1816457.png">

**Comment by abhinayagarwal** [comment] 2019-02-15 05:11
I haven't tested the javadoc jars, but they are released.

May be this bug can be a reason for a buggy javadoc jar - https://github.com/controlsfx/controlsfx/blob/9.0.0/build.gradle#L165

**Comment by Adyel** [comment] 2019-02-15 05:17
@abhinayagarwal How do I add the snapshot to gradle dependency?

**Comment by abhinayagarwal** [comment] 2019-02-15 08:23
@Adyel That seems right. FYI, I have bumped the version to `11.0.0` and released `11.0.0-SNAPSHOT`.

**Comment by HGuillemet** [comment] 2019-02-15 12:19
Will 11.0.0 be released as a named module (include a module-info.class ?)

**Comment by Adyel** [comment] 2019-02-16 06:12
@abhinayagarwal I am still having issues :face_with_head_bandage: 
![controlfx](https://user-images.githubusercontent.com/4653623/52895378-c2613b00-31e3-11e9-8671-8d91014bcadb.png)

`Caused by: java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in unnamed module @0x5db73277) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to unnamed module @0x5db73277
`
This time `TextFields.bindAutoCompletion()` is causing the issue.

```java
// INFO: Suggestion
List<String> suggestion = movieDetailsList.stream().map(MovieDetails::getFileName).collect(Collectors.toList());
TextFields.bindAutoCompletion(searchField, suggestion);
```

**Comment by zcaudate** [comment] 2019-02-16 06:20
docs are available for version 8 but not version 9.

I'm getting this message:

<img width="388" alt="screen shot 2019-02-16 at 2 15 31 pm" src="https://user-images.githubusercontent.com/1455572/52895467-f2193e80-31f5-11e9-945a-c4d057c5644d.png">

**Comment by Inalkar** [comment] 2019-02-16 10:03
@abhinayagarwal I have another issue with ListSelectionView component:

> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public static com.sun.javafx.css.StyleManager com.sun.javafx.css.StyleManager.getInstance() accessible: module javafx.graphics does not "exports com.sun.javafx.css" to module org.controlsfx.controls
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at org.controlsfx.controls/impl.org.controlsfx.ReflectionUtils.addUserAgentStylesheet(ReflectionUtils.java:225)
	at org.controlsfx.controls/org.controlsfx.glyphfont.GlyphFont.<clinit>(GlyphFont.java:57)

**Comment by HGuillemet** [comment] 2019-02-16 11:41
Hi,
I tested the snapshot in a module path and still gets:
```
java.lang.IllegalAccessError: superclass access check failed: class impl.org.controlsfx.behavior.RangeSliderBehavior (in module org.controlsfx.controls) cannot access class com.sun.javafx.scene.control.behavior.BehaviorBase (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to module org.controlsfx.controls

java.lang.IllegalAccessError: class impl.org.controlsfx.behavior.RangeSliderBehavior (in module org.controlsfx.controls) cannot access class com.sun.javafx.scene.control.inputmap.InputMap$Mapping (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.inputmap to module org.controlsfx.controls

java.lang.IllegalAccessError: superinterface check failed: class impl.org.controlsfx.skin.RangeSliderSkin$5$1 (in module org.controlsfx.controls) cannot access class com.sun.javafx.scene.traversal.Algorithm (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.traversal to module org.controlsfx.controls
```
A  `--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls --add-exports=javafx.controls/com.sun.javafx.scene.control.inputmap=org.controlsfx.controls --add-exports=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls` on the command line works around these errors.

**Comment by abhinayagarwal** [comment] 2019-02-18 08:30
Hi @Inalkar @HGuillemet,

Please keep in mind ControlsFX still uses a lot of internal APIs and you need to add the necessary JVM args depending on the control you use. For a list of all the args, please check the [build file](https://github.com/controlsfx/controlsfx/blob/9.0.0/build.gradle#L1).

**Comment by thomasnield** [comment] 2019-02-18 15:17
Hey ya'll, keep in mind you can use JitPack to create a dependency on a snapshot or particular commit using Gradle or Maven:

https://jitpack.io/#controlsfx/controlsfx

**Comment by Adyel** [comment] 2019-02-18 15:22
@abhinayagarwal  Can you please help me to setup proper gradle with JVM args :(

**Comment by bingo-tango** [comment] 2019-02-18 16:40
Tested my app with the 11.0.0-SNAPSHOT, works now with OpenJFX 11.0.2. I'm only using some PropertySheet and PropertyEditor classes though, so it's a minimal test. Thanks so much!

@Adyel  I added the VM args mentioned to my run configuration. I'm using Eclipse, but IntelliJ also has run configurations where you can specify VM args to use at app launch.

**Comment by Adyel** [comment] 2019-02-18 16:43
@bingo-tango  Can you please add a screenshot so I can understand it better. :)

**Comment by bingo-tango** [comment] 2019-02-18 16:58
@Adyel You should be able to go to Run -> Edit Configurations -> (select your project's Gradle run config). There should be a VM options box in the dialog, put them there. 
![screen shot 2019-02-18 at 11 57 54 am](https://user-images.githubusercontent.com/7428930/52966126-7e517000-3374-11e9-9c1a-ed66deabeb45.png)

**Comment by Adyel** [comment] 2019-02-18 17:02
@bingo-tango  Thank you so much :smile:

**Comment by mipastgt** [comment] 2019-02-20 08:53
I am using ControlsFX in a project on a Mac. For testing I just bumped up the version to 11.0.0.-SNAPSHOT and the result is that maven pulled in all the Linux dependencies of JavaFX. Is it possible the is some explicit Linux dependency in the ControlsFX POM? See attached screen shots.

<img width="417" alt="mvn-controlsfx-9 0 0" src="https://user-images.githubusercontent.com/16735714/53078531-b1227200-34f4-11e9-9e55-9b01dee52cb0.png">
<img width="413" alt="mvn-controlsfx-11 0 0-snapshot" src="https://user-images.githubusercontent.com/16735714/53078548-baabda00-34f4-11e9-9f7f-3307d8686d1c.png">

**Comment by mipastgt** [comment] 2019-02-20 09:28
I just had a look at it. You explicitly specify
`      <classifier>linux</classifier>
`
in your JavaFX dependencies which you shouldn't.

**Comment by abhinayagarwal** [comment] 2019-03-03 19:24
Hi All,

ControlsFX 11.0.0-RC1 is now released and available at maven central - https://repo1.maven.org/maven2/org/controlsfx/controlsfx/11.0.0-RC1/

Please test and report bugs, if any :)

**Comment by mipastgt** [comment] 2019-03-03 19:30
Why do you still have the <classifier>linux</classifier> in the POM?
Not all systems are Linux :-)

Am 03.03.19 um 20:24 schrieb Abhinay Agarwal:

**Comment by abhinayagarwal** [comment] 2019-03-03 20:04
Aha, good catch. I will remove it and try to release RC-2.

**Comment by jasons2000** [comment] 2019-03-03 21:07
is this purely a technical release, or are there any  new features?

**Comment by abhinayagarwal** [comment] 2019-03-04 06:09
@mipastgt RC2 is now available without classifiers.

@jasons2000 There are a few bug fixes in the release. These releases are still RC and the final release may have a few changes baked in.

**Comment by jasons2000** [comment] 2019-03-04 11:18
Appreciate the work on this, but with JDK 12 out at the end of the month, will we need another controlsfx release to match this?

**Comment by dlemmermann** [comment] 2019-03-04 11:21
Java 11 (actually Java 9) broke the API and OpenJFX changed the way apps are assembled (JavaFX as dependencies), hence a Release 11 was required. 
Java 12 does not do that, so a new release is not needed.

**Comment by abhinayagarwal** [comment] 2019-03-04 11:23
Personally, I do not think ControlsFX should follow the Java/FX release cycle anymore as it used to do in the past.

**Comment by kuhjunge** [comment] 2019-03-05 11:44
> 
> 
> @abhinayagarwal I am still having issues 🤕
> ![controlfx](https://user-images.githubusercontent.com/4653623/52895378-c2613b00-31e3-11e9-8671-8d91014bcadb.png)
> 
> ```
> Caused by: java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in unnamed module @0x5db73277) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to unnamed module @0x5db73277
> ```
> 
> This time `TextFields.bindAutoCompletion()` is causing the issue.
> 
> ```java
> // INFO: Suggestion
> List<String> suggestion = movieDetailsList.stream().map(MovieDetails::getFileName).collect(Collectors.toList());
> TextFields.bindAutoCompletion(searchField, suggestion);
> ```

I have the same issue, but only on Windows, not on Linux with the RC2 release.  Setting VM options didn't work for me either.

**Comment by Eng-Fouad** [comment] 2019-03-05 12:39
I can confirm that controlsfx-11.0.0-RC2 is working well on application that used controlsfx-9.0.0 before:

I just replaced the module name from `controlsfx` to `org.controlsfx.controls`.
Also, I had to include `javafx.media` and `javafx.web` though I am not using them. So I added them as compileOnly dependencies in `build.gradle`:

    dependencies {
          // JavaFX
          implementation name: "javafx.base-11.0.1"
          implementation name: "javafx.controls-11.0.1"
          implementation name: "javafx.fxml-11.0.1"
          implementation name: "javafx.graphics-11.0.1"
          implementation name: "javafx.swing-11.0.1"
          compileOnly name: "javafx.media-11.0.1"
          compileOnly name: "javafx.web-11.0.1"
          //...
    }

Here is a snippet of `build.gradle` from the module that contains the main class:

```
project.ext.moduleName = 'io.fouad.launcher'

apply plugin: 'application'

mainClassName = 'io.fouad.AppLauncher'

run {
    inputs.property("moduleName", moduleName)
    doFirst {
        jvmArgs = [
                '--module-path', classpath.asPath,
                '--add-modules', 'ALL-MODULE-PATH',
                "--add-opens=javafx.base/com.sun.javafx.runtime=org.controlsfx.controls",
                "--add-opens=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls",
                "--add-opens=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls",
                "--add-opens=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls",
                "--add-opens=javafx.controls/com.sun.javafx.scene.control=org.controlsfx.controls",
                "--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls",
                "--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls",
                "--add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls",
                '-Djava.library.path=../build-resources/javafx-dlls/64-bit;../build-resources/javafx-dlls/64-bit-extra',
                '-Djavafx.preloader=io.fouad.AppPreloader',
                '--module', "$moduleName/$mainClassName"
        ]
        classpath = files()
    }
}
```

**Comment by abhinayagarwal** [comment] 2019-03-06 18:48
It would be great if we can get rid of the `javafx.web` and `javafx.media` dependencies out of controlsfx. May be move the controls which need these modules to a new project under ControlsFX. Thoughts?

**Comment by jschlade** [comment] 2019-03-12 16:19
Hi @abhinayagarwal,

Just checking in to see if we're close to releasing this?

Thanks

**Comment by abhinayagarwal** [comment] 2019-03-12 17:55
Hi @jschlade,

I have been working on a few issues before releasing the final version. PR #1107 was recently merged and will allow users to use `AutoCompletePopup`, `BreadCrumbBar`, `HyperlinkLabel` without depending on the private `com.sun.javafx.event.EventHandlerManager`.

Currently, I am trying to fix #1109. Once this is fixed, `BreadCrumbBar` should be usable under ControlsFX 11.0.0.

**Comment by jschlade** [comment] 2019-03-12 20:45
@abhinayagarwal thanks again for doing all that you do for this project. Truly appreciated.

**Comment by nx10** [comment] 2019-03-14 17:36
If anyone else is struggling to get this working with the gradle application plugin:
You can add jvm args like this:

```
application {
    applicationDefaultJvmArgs =  [
            "--add-opens=javafx.base/com.sun.javafx.runtime=org.controlsfx.controls",
            "--add-opens=javafx.base/com.sun.javafx.collections=org.controlsfx.controls",
            "--add-opens=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls",
            "--add-opens=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls",
            "--add-opens=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls",
            "--add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls",
            "--add-opens=javafx.controls/com.sun.javafx.scene.control=org.controlsfx.controls",
            "--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls",
            "--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls"
    ]
}
```

**Comment by SimonScholz** [comment] 2019-04-02 09:04
> If anyone else is struggling to get this working with the gradle application plugin:
> You can add jvm args like this:
> 
> ```
> application {
>     applicationDefaultJvmArgs =  [
>             "--add-opens=javafx.base/com.sun.javafx.runtime=org.controlsfx.controls",
>             "--add-opens=javafx.base/com.sun.javafx.collections=org.controlsfx.controls",
>             "--add-opens=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls",
>             "--add-opens=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls",
>             "--add-opens=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls",
>             "--add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls",
>             "--add-opens=javafx.controls/com.sun.javafx.scene.control=org.controlsfx.controls",
>             "--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls",
>             "--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls"
>     ]
> }
> ```

Unfortunately I am getting the following error, when I use the --add-opens args :

```
WARNING: Unknown module: javafx.graphics specified to --add-opens
WARNING: Unknown module: javafx.controls specified to --add-opens
WARNING: Unknown module: javafx.controls specified to --add-opens
WARNING: Unknown module: javafx.controls specified to --add-opens
WARNING: Unknown module: javafx.base specified to --add-opens
WARNING: Unknown module: javafx.graphics specified to --add-opens
WARNING: Unknown module: javafx.graphics specified to --add-opens
WARNING: Unknown module: javafx.base specified to --add-opens
WARNING: Unknown module: javafx.graphics specified to --add-opens
```

Are there any plans to get rid of the usage of internal apis?

IMO we should spot the internal api usages and replace them by using proper exported apis if possible.

**Comment by SimonScholz** [comment] 2019-04-02 09:06
I  am currently having problems with the `com.sun.javafx.css.StyleManager
`
```
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 39 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public static com.sun.javafx.css.StyleManager com.sun.javafx.css.StyleManager.getInstance() accessible: module javafx.graphics does not "exports com.sun.javafx.css" to unnamed module @41765f9b
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at impl.org.controlsfx.ReflectionUtils.addUserAgentStylesheet(ReflectionUtils.java:225)
	at org.controlsfx.glyphfont.GlyphFont.<clinit>(GlyphFont.java:57)
	... 44 more
```

**Comment by danielpeintner** [comment] 2019-04-05 12:37
Same issue when trying to use `'org.controlsfx:controlsfx:11.0.0-RC2'`
 :-(

**Comment by nx10** [comment] 2019-04-08 11:53
> > If anyone else is struggling to get this working with the gradle application plugin:
> > You can add jvm args like this:
> > ```
> > application {
> >     applicationDefaultJvmArgs =  [
> >             "--add-opens=javafx.base/com.sun.javafx.runtime=org.controlsfx.controls",
> >             "--add-opens=javafx.base/com.sun.javafx.collections=org.controlsfx.controls",
> >             "--add-opens=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls",
> >             "--add-opens=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls",
> >             "--add-opens=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls",
> >             "--add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls",
> >             "--add-opens=javafx.controls/com.sun.javafx.scene.control=org.controlsfx.controls",
> >             "--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls",
> >             "--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls"
> >     ]
> > }
> > ```
> 
> Unfortunately I am getting the following error, when I use the --add-opens args :
> 
> ```
> WARNING: Unknown module: javafx.graphics specified to --add-opens
> WARNING: Unknown module: javafx.controls specified to --add-opens
> WARNING: Unknown module: javafx.controls specified to --add-opens
> WARNING: Unknown module: javafx.controls specified to --add-opens
> WARNING: Unknown module: javafx.base specified to --add-opens
> WARNING: Unknown module: javafx.graphics specified to --add-opens
> WARNING: Unknown module: javafx.graphics specified to --add-opens
> WARNING: Unknown module: javafx.base specified to --add-opens
> WARNING: Unknown module: javafx.graphics specified to --add-opens
> ```
> Are there any plans to get rid of the usage of internal apis?
> 
> IMO we should spot the internal api usages and replace them by using proper exported apis if possible.

Just a shot in the dark here but did you make sure to require the javafx modules in your module-info.java?

**Comment by danielpeintner** [comment] 2019-04-08 13:23
Mhh, it seems to be associated with glyphs.

This code snippet works just fine

```
Button b = new Button("Press");
```

but when I try to add glyphs to it it fails.

```
Button b = new Button("Press"
      , (new org.controlsfx.glyphfont.FontAwesome()).create(org.controlsfx.glyphfont.FontAwesome.Glyph.ANGLE_DOWN)
);
```


Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public static com.sun.javafx.css.StyleManager com.sun.javafx.css.StyleManager.getInstance() accessible: module javafx.graphics does not "exports com.sun.javafx.css" to unnamed module @659cd41c ...

**Comment by nx10** [comment] 2019-04-08 13:30
Try to change 

```
"--add-opens=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls"
```
to

```
"--add-opens=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED"
```

**Comment by danielpeintner** [comment] 2019-04-08 13:41
@nx10 thanks!

FYI: Depending on the used controls some more `"--add-opens"` have to be added.

e.g., for HyperlinkLabel

`"--add-opens=javafx.base/com.sun.javafx.event=ALL-UNNAMED"`

**Comment by danielpeintner** [comment] 2019-04-12 08:31
FYI: I created another issue (see https://github.com/controlsfx/controlsfx/issues/1135) about `TableFilter` which I think would be good to be solved before 
 release v11.

**Comment by mipastgt** [comment] 2019-04-14 12:08
Should the version of JavaFX not be bumped up to 12. Why stick with 11 if this is now obsolete and has nothing to do with a potential compatibility with Java 11. JavaFX 12 is the latest JavaFX release and is still compatible with Java 11.

**Comment by Adyel** [comment] 2019-04-14 12:23
@mipastgt  Because maybe 11 is the LTS release. Java 12 is here for 6 months while Java 11 will stay for a long time.

**Comment by mipastgt** [comment] 2019-04-14 12:33
@Adyel I thought I had made that clear. This issue has nothing to do with the Java 11 LTS release. Even if you want to stick with that you could still use JavaFX 12. The problem now is that ControlsFX11 has an explicit dependency on JavaFX 11 and if you use it in a project maven will pull in an outdated version of JavaFX if you do not explicitly override this.

**Comment by abhinayagarwal** [comment] 2019-04-14 16:37
@mipastgt AFAIK, ControlsFX versions have always being tightly bound to the JavaFX version :)

Please note, you can always use ControlsFX 11 with JavaFX 12 by excluding transitive dependencies and explicitly declaring JavaFX 12 dependencies in Maven or Gradle.

**Comment by abhinayagarwal** [comment] 2019-04-14 17:14
https://github.com/controlsfx/controlsfx/issues/1137#issuecomment-483020099 : ControlsFX 11.0.0 is now available in staging repository.

**Comment by mipastgt** [comment] 2019-04-14 18:10
@abhinayagarwal Yes, you can but this can also result in hard to track down errors. For example: I have an explicit dependency to javafx.controls of JavaFX 13 in my POM and I expect javafx.graphics and javafx.base to be resolved transitively to the same version. But this is not happening because ControlsFX has this dependency on JavaFX 11. So Maven happily pulls in graphics and base from 11 and the rest from 13 which results in potential conflicts at runtime. Of course I can override this behaviour but only if I am aware of this pitfall and I am not sure that everybody will be aware of this.

**Comment by abhinayagarwal** [comment] 2019-04-15 06:07
@mipastgt Maven dependencies *may have* transitive dependencies. This is very well known. I am not sure what do you want to change in ControlsFX. If we just update JavaFX dependencies to 12, you will still need to exclude them if you want to use JavaFX 13.

**Comment by jchildress** [comment] 2019-04-16 02:40
Works with JavaFX 12
```
    implementation ('org.controlsfx:controlsfx:11.0.0' ) {
        exclude group: 'org.openjfx', module: 'javafx-fxml'
        exclude group: 'org.openjfx', module: 'javafx-web'
        exclude group: 'org.openjfx', module: 'javafx-media'
    }
```

**Comment by mipastgt** [comment] 2019-04-16 08:14
@abhinayagarwal My primary concern is that I do not want ControlsFX to pull in an outdated version of JavaFX. Just change the dependency to 12, which is the official current version, and if anybody wants to use another version he can override the dependency.
Just my two €cent.

**Comment by Eng-Fouad** [comment] 2019-04-16 10:22
> It would be great if we can get rid of the `javafx.web` and `javafx.media` dependencies out of controlsfx. May be move the controls which need these modules to a new project under ControlsFX. Thoughts?

How about using `requires static javafx.web;` instead of using `requires transitive javafx.web;`?

**Comment by nx10** [comment] 2019-04-16 12:56
> @abhinayagarwal My primary concern is that I do not want ControlsFX to pull in an outdated version of JavaFX. Just change the dependency to 12, which is the official current version, and if anybody wants to use another version he can override the dependency.

JavaFX 11 is the LTS Version JavaFX 12 will only have 6 month of support: https://gluonhq.com/announcing-javafx-12/

**Comment by ttimbul** [comment] 2019-04-16 14:59
@mipastgt I would suggest that you are placing too many expectations on your version management system if you're expecting it to magically pull in versions that you haven't told it you care about.

A possible solution may be for you to declare the required versions as properties, which you can amend as necessary when the next Java version comes out, such as in maven:
`<java.compiler.source.version>12</java.compiler.source.version>`
`<java.compiler.target.version>12<java.compiler.target.version>`
`<javafx.version>12.0.0</javafx.version>`
`<controlsfx.version>11.0.0</controlsfx.version>`

You can exclude and explicitly declare any other artifacts that you can't work with.
Why should each release of controlsfx potentially break compatibility or depend on a Java version that is higher than absolutely necessary?
Also the compiler can work with source 12, target 11. So you could still use the latest language features while supporting the LTS version?

**Comment by mipastgt** [comment] 2019-04-16 16:43
> @mipastgt I would suggest that you are placing too many expectations on your version management system if you're expecting it to magically pull in versions that you haven't told it you care about.

I never said that or asked for it.

> A possible solution may be for you to declare the required versions as properties, which you can amend as necessary when the next Java version comes out, such as in maven:
> `<java.compiler.source.version>12</java.compiler.source.version>`
> `<java.compiler.target.version>12<java.compiler.target.version>`
> `<javafx.version>12.0.0</javafx.version>`
> `<controlsfx.version>11.0.0</controlsfx.version>`

That's what I do all the time.

> You can exclude and explicitly declare any other artifacts that you can't work with.
> Why should each release of controlsfx potentially break compatibility or depend on a Java version that is higher than absolutely necessary?
> Also the compiler can work with source 12, target 11. So you could still use the latest language features while supporting the LTS version?

I did not talk about Java versions. I talked about JavaFX versions.

But let's stop this fruitless discussion now.

**Comment by abhinayagarwal** [comment] 2019-04-19 07:52
#1137 ControlsFX 11.0.0 is now available \o/

Thank you everyone for testing and providing feedback.

**Closed by abhinayagarwal** 2019-04-19 07:52 UTC
Labels: housekeeping

**Comment by pseigo** [comment] 2019-04-23 19:03
> Try to change
> 
> ```
> "--add-opens=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls"
> ```
> to
> 
> ```
> "--add-opens=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED"
> ```

Thank you! I was getting errors using FontAwesome glyphs in fxml. Putting the second line in my VM options fixed it. Here are the errors I was getting, using controlsfx-11.0.0, openjdk 11.0.3 2019-04-16 and openjfx 11.0.2+1-1 in IntelliJ IDEA on Kubuntu 19.04,

[Error log](https://gist.github.com/pseigo/d2325c6668af427129d94e5745f383fc). Relevant lines are 19, 34 and 68.

[The culprit FXML file](https://gist.github.com/pseigo/a37d5c1e0058af75b7b7ada7d0940e0c). Relevant lines here are 20 and 23. For quick reference,

```xml
<Glyph fontFamily="FontAwesome" fontSize="32.0" icon="USER" style="-fx-cursor: hand;" />
```

is the line that caused my problems.

**Comment by FelipeAumannRS** [comment] 2021-05-03 13:09
> If anyone else is struggling to get this working with the gradle application plugin:
> You can add jvm args like this:
> 
> ```
> application {
>     applicationDefaultJvmArgs =  [
>             "--add-opens=javafx.base/com.sun.javafx.runtime=org.controlsfx.controls",
>             "--add-opens=javafx.base/com.sun.javafx.collections=org.controlsfx.controls",
>             "--add-opens=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls",
>             "--add-opens=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls",
>             "--add-opens=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls",
>             "--add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls",
>             "--add-opens=javafx.controls/com.sun.javafx.scene.control=org.controlsfx.controls",
>             "--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls",
>             "--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls"
>     ]
> }
> ```

got these warnings, for some reason all of the "--add-opens" arguments are not working:

`WARNING: Unknown module: org.controlsfx.controls specified to --add-opens
WARNING: Unknown module: org.controlsfx.controls specified to --add-opens
WARNING: Unknown module: org.controlsfx.controls specified to --add-opens
WARNING: Unknown module: org.controlsfx.controls specified to --add-opens
WARNING: Unknown module: org.controlsfx.controls specified to --add-opens
WARNING: Unknown module: org.controlsfx.controls specified to --add-opens
WARNING: Unknown module: org.controlsfx.controls specified to --add-opens
WARNING: Unknown module: org.controlsfx.controls specified to --add-opens
WARNING: Unknown module: org.controlsfx.controls specified to --add-opens`

**Comment by FelipeAumannRS** [comment] 2021-05-03 13:21
> Works with JavaFX 12
> 
> ```
>     implementation ('org.controlsfx:controlsfx:11.0.0' ) {
>         exclude group: 'org.openjfx', module: 'javafx-fxml'
>         exclude group: 'org.openjfx', module: 'javafx-web'
>         exclude group: 'org.openjfx', module: 'javafx-media'
>     }
> ```

where should I implement this code piece? Inside "dependencies?" (just a guess)?
