### ISSUE TITLE
Can't open project in Eclipse

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#1057] opened 2018-07-05 12:02 UTC
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/866) by Mikael Wallin (Bitbucket: [miwashi](https://bitbucket.org/miwashi), GitHub: Unknown).**

----------------------------------------

As root project is named same as a subproject, Eclipse claims project already imported when importing project.

Eclipse Oxygen.3a Release (4.7.3a)
Buildship 2.2.1

**Comment by abhinayagarwal** [comment] 2019-06-19 14:46
Duplicate of #937.

**Closed by abhinayagarwal** 2019-06-19 14:46 UTC
Labels: bug, duplicate
