### ISSUE TITLE
GridView makes application crash

### ISSUE THREAD

**Issue by Ep0chalypse** [controlsfx/controlsfx#1400] opened 2021-10-17 01:40 UTC
I'm using controlsfx v11.1.0 inside a simple javafx project. I add a GridView to my fxml file and reference it in  my view's controller. But when I try to set a observable list to it, my app crashes with a cryptic error message that I get 0 google results for. 

```
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.control.IndexedCell.updateIndex(int)" because "<parameter1>" is null
	at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1807)
	at javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1791)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2966)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2949)
	at javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(VirtualFlow.java:3021)
	at javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(VirtualFlow.java:3013)
	at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1052)
	at javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:885)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:899)
	at impl.org.controlsfx.skin.GridViewSkin.updateItemCount(GridViewSkin.java:134)
	at impl.org.controlsfx.skin.GridViewSkin.updateGridViewItems(GridViewSkin.java:99)
	at impl.org.controlsfx.skin.GridViewSkin.<init>(GridViewSkin.java:52)
	at org.controlsfx.control.GridView.createDefaultSkin(GridView.java:142)
	at javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.scene.control.Control.doProcessCSS(Control.java:900)
	at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Node.processCSS(Node.java:9456)
	at javafx.scene.Scene.doCSSPass(Scene.java:572)
	at javafx.scene.Scene.preferredSize(Scene.java:1774)
	at javafx.scene.Scene$2.preferredSize(Scene.java:396)
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.stage.Window$12.invalidated(Window.java:1114)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.stage.Window.setShowing(Window.java:1190)
	at javafx.stage.Window.show(Window.java:1205)
	at javafx.stage.Stage.show(Stage.java:273)
	at com.example.MyApplication.start(MyApplication.kt:32)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	... 1 more
```

**Comment by Siedlerchr** [comment] 2021-12-01 19:14
I can confirm the bug for javafx 17.0.1 and the workaround using Platform.runLater works.
```

Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.control.IndexedCell.updateIndex(int)" because "<parameter1>" is null
	at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1807) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1791) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2966) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2949) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(VirtualFlow.java:3021) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(VirtualFlow.java:3013) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1052) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:885) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113) ~[javafx-base-17.0.1-mac.jar:?]
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148) ~[javafx-base-17.0.1-mac.jar:?]
	at javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:899) ~[javafx-controls-17.0.1-mac.jar:?]
	at impl.org.controlsfx.skin.GridViewSkin.updateItemCount(GridViewSkin.java:134) ~[controlsfx-11.1.0.jar:?]
	at impl.org.controlsfx.skin.GridViewSkin.updateGridViewItems(GridViewSkin.java:99) ~[controlsfx-11.1.0.jar:?]
	at impl.org.controlsfx.skin.GridViewSkin.<init>(GridViewSkin.java:52) ~[controlsfx-11.1.0.jar:?]
	at org.controlsfx.control.GridView.createDefaultSkin(GridView.java:142) ~[controlsfx-11.1.0.jar:?]
	at javafx.scene.control.Control.doProcessCSS(Control.java:897) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.Control$1.doProcessCSS(Control.java:89) ~[javafx-controls-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67) ~[javafx-controls-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.control.PopupControl$CSSBridgeHelper.superProcessCSSImpl(PopupControl.java:1232) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.PopupControl$CSSBridgeHelper.superProcessCSS(PopupControl.java:1228) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.PopupControl$CSSBridge.doProcessCSS(PopupControl.java:1193) ~[javafx-controls-17.0.1-mac.jar:?]
	at javafx.scene.control.PopupControl$CSSBridgeHelper.processCSSImpl(PopupControl.java:1237) ~[javafx-controls-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Node.processCSS(Node.java:9456) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Scene.doCSSPass(Scene.java:572) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Scene.preferredSize(Scene.java:1774) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.scene.Scene$2.preferredSize(Scene.java:396) ~[javafx-graphics-17.0.1-mac.jar:?]
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.stage.Window$12.invalidated(Window.java:1114) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110) ~[javafx-base-17.0.1-mac.jar:?]
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145) ~[javafx-base-17.0.1-mac.jar:?]
	at javafx.stage.Window.setShowing(Window.java:1190) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.stage.Window.show(Window.java:1205) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.stage.PopupWindow.showImpl(PopupWindow.java:475) ~[javafx-graphics-17.0.1-mac.jar:?]
	at javafx.stage.PopupWindow.show(PopupWindow.java:420) ~[javafx-graphics-17.0.1-mac.jar:?]
	at org.controlsfx.control.PopOver.show(PopOver.java:463) ~[controlsfx-11.1.0.jar:?]
	at org.controlsfx.control.PopOver.show(PopOver.java:386) ~[controlsfx-11.1.0.jar:?]
	at org.controlsfx.control.PopOver.show(PopOver.java:320) ~[controlsfx-11.1.0.jar:?]
	at org.controlsfx.control.PopOver.show(PopOver.java:288) ~[controlsfx-11.1.0.jar:?]
	at org.jabref.gui.groups.GroupDialogView.openIconPicker(GroupDialogView.java:249) ~[main_/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:77) ~[javafx-base-17.0.1-mac.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275) ~[javafx-base-17.0.1-mac.jar:?]
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84) ~[javafx-fxml-17.0.1-mac.jar:?]
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1854) ~[javafx-fxml-17.0.1-mac.jar:?]
```

**Comment by permiakovsa** [comment] 2021-12-22 14:04
Confirm the bug, but runlater-workaround doesnt work

**Comment by NathanielAJohnson** [comment] 2022-05-06 16:29
Can confirm same NPE with 17,18,19-ea+5
```
javafx {
    version = '19-ea+5'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.web', 'javafx.media']
}
```
Works fine with javafx 16

**Comment by abhinayagarwal** [comment] 2022-05-06 16:39
Can someone add a [SSCCE](http://sscce.org/) to reproduce this bug?

**Comment by NathanielAJohnson** [comment] 2022-05-06 16:44
> Can someone add a [SSCCE](http://sscce.org/) to reproduce this bug?

I will get one together.  it may take me a day or two.

**Comment by NathanielAJohnson** [comment] 2022-05-06 17:14
In a bit of a hurry so I haven't copied out the files into this thread but this should do the trick.

https://github.com/NathanielAJohnson/demo

**Comment by NathanielAJohnson** [comment] 2022-05-07 00:04
`build.gradle`

```gradle
plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.10'
    id 'org.beryx.jlink' version '2.24.1'
}

group 'com.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.8.2'
}

sourceCompatibility = '17'
targetCompatibility = '17'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

application {
    mainModule = 'com.example.demo'
    mainClass = 'com.example.demo.HelloApplication'
}

javafx {
    version = '17.0.1'
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
    implementation('org.controlsfx:controlsfx:11.1.1')

    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
}

test {
    useJUnitPlatform()
}

jlink {
    imageZip = project.file("${buildDir}/distributions/app-${javafx.platform.classifier}.zip")
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'app'
    }
}

jlinkZip {
    group = 'distribution'
}
```
`/src/main/java/com/example/demo`
```java
package com.example.demo;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import org.controlsfx.control.GridView;
import org.controlsfx.control.cell.ColorGridCell;

import java.util.ArrayList;
import java.util.Random;

public class HelloApplication extends Application {
    @Override
    public void start(Stage stage) {
        this.stage = stage;
        showPrimaryScene(stage);
        stage.setTitle("Rollplay Online");
        stage.show();
    }

    private void showPrimaryScene(Stage stage) {
        primaryScene = new Scene(new MainForm(), 800, 600);

        stage.setScene(primaryScene);
    }

    private Scene primaryScene;
    private Stage stage;

    public static void main(String[] args) {
        launch();
    }
}
class MainForm extends BorderPane {

    public MainForm() {
        super();
        Random r = new Random(System.currentTimeMillis());
        ArrayList<Color> list = new ArrayList<>();
        for(int i = 0; i < 500; i++) {
            list.add(new Color(r.nextDouble(), r.nextDouble(), r.nextDouble(), 1.0));
        }
        ObservableList<Color> olist= FXCollections.observableList(list);
        GridView<Color> myGrid = new GridView<>(olist);
        myGrid.setCellFactory(gridView -> new ColorGridCell());
        this.setCenter(myGrid);
    }
}
```
`/src/main/java/module-info.java`
```java
module com.example.demo {
    requires javafx.controls;
    requires javafx.fxml;

    requires org.controlsfx.controls;

    opens com.example.demo to javafx.fxml;
    exports com.example.demo;
}
```

**Comment by abhinayagarwal** [comment] 2022-05-08 07:45
This issue is only reproducible with JavaFX 17 and later. There were some VirtualFlow changes that went into JavaFX 17 and the control needs to take them into account.

**Comment by johanvos** [comment] 2022-05-08 18:40
Before JavaFX 17, the VirtualFlow did not take into account the size of individual cells when calculating the current relative position (a value between 0 and 1). That leads to major issues when scrolling flows with irregular cells. 
This issue is tracked in https://bugs.openjdk.java.net/browse/JDK-8089589 and it was fixed in JavaFX 17.

That fix requires the VirtualFlow to be able to calculate the size of the cells. (Note: for performance reasons, we don't calculate the size of all cells at once, but start with an estimate and gradually improve the estimate).
Calculating the size of a cell requires a cellFactory to be present. Hence, the cellFactory should be set before any operations on the VirtualFlow can be done.

The crash you see here happens because the cellFactory is not set yet, and a call to e.g. VirtualFlow.setCellCount() will throw an exception since it will try to update the estimated size (which won't work since the cellFactory is null).
I think there are two action items here:
* In GridViewSkin, the setCellFactory should be called before e.g. updateGridViewItems()
* The VirtualFlow implementation in OpenJFX should not throw a NullPointerException in case there is no cellFactory set. I'm not sure what the default implementation should do, though.

**Closed** 2022-05-21 12:36 UTC
Labels: bug
